defaults: &defaults
  appid: 157
  ip: 109.235.143.113
  locale: de
  offer_types: 112

development:
  <<: *defaults
  api_url: "http://api.sponsorpay.com"

test:
  <<: *defaults
  api_url: "http://example.testapi"
  ip: 212.45.111.17

#===---

production:
  <<: *defaults

